version: "3.8"

services:
  app:
    build: .
    container_name: pdf-review
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MAX_FILE_SIZE=10485760 # 10MB
      - MAX_MEMORY=2048 # 2GB
    volumes:
      - pdf-data:/app/data
      - pdf-logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "1"
          memory: 1G

volumes:
  pdf-data:
  pdf-logs:
